backend:
  name: github
  repo: geops/mapset.io
  base_url: https://mapset.io/
  auth_endpoint: api/auth
  branch: master

media_folder: static/img
public_folder: /img
local_backend: true

publish_mode: editorial_workflow

collections:
  - label: "Guide Locales"
    name: "guide"
    folder: "src/data/guide"
    extension: "json"
    create: true
    fields:
      - {label: "Sprache", name: "title", widget: "string"}
      - {
        label: "Features",
        name: "features",
        widget: "list",
        fields:
          [
          {
            label: "Label", name: "label", widget: "string"
          },
          {
            label: "Mapset Icon",
            name: "mapsetIcon",
            widget: "string",
            required: false,
          },
          {
            label: "Content",
            name: "content",
            widget: "list",
            allow_add: true,
            fields:
              [
              {
                label: "Überschrift",
                name: "heading",
                widget: "markdown",
                required: false,
              },
              {
                label: "Mapset Icon",
                name: "mapsetIcon",
                widget: "string",
                required: false,
              },
              {
                label: "Text", name: "text", widget: "markdown"
              },
              {
                label: "Login restricted",
                name: "loginRestricted",
                widget: "boolean",
                required: false,
              },
              {
                label: "CD restricted",
                name: "cdRestricted",
                widget: "boolean",
                required: false,
              },
              ]
          }
          ]
      }
  - label: "Inhalt Locales"
    name: "inhalt"
    folder: "src/data/index"
    extension: "json"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index"}
      - {label: "Title", name: "title", widget: "string"}
      - {
        label: "Inhalt der Indexseite",
        name: "content",
        widget: "object",
        fields:
          [
            {label: "page header", name: "page header", widget: "string"},
            {label: "page header description", name: "page header description", widget: "string"},
            {label: "specification description", name: "specification description", widget: "string"},
            {label: "price description", name: "price description", widget: "string"},
            {label: "conditions text eu", name: "conditions text", widget: "markdown"},
            {label: "conditions text ch", name: "conditions text", widget: "markdown"},
            {label: "included in price", name: "included in price", widget: "markdown"},
            {label: "contact description", name: "contact description", widget: "string"},
          ]
      }
      - {
        label: "Allgemeine Bezeichnungen",
        name: "generic",
        widget: "object",
        fields:
          [
            {label: "powered by", name: "powered by", widget: "string"},
            {label: "Benefits", name: "Benefits", widget: "string"},
            {label: "Guide", name: "Guide", widget: "string"},
            {label: "So funktioniert's", name: "So funktioniert's", widget: "string"},
            {label: "Preise", name: "Preise", widget: "string"},
            {label: "Kontakt", name: "Kontakt", widget: "string"},
            {label: "Demo", name: "Demo", widget: "string"},
            {label: "Anmelden", name: "Anmelden", widget: "string"},
            {label: "Zufriedene Kunden", name: "Zufriedene Kunden", widget: "string"},
            {label: "Im Preis inbegriffen sind:", name: "Im Preis inbegriffen sind:", widget: "string"},
            {label: "Noch Fragen ?", name: "Noch Fragen ?", widget: "string"},
            {label: "Ihr persönlicher Kontakt", name: "Ihr persönlicher Kontakt", widget: "string"},
            {label: "Besuchen Sie uns auf Twitter", name: "Besuchen Sie uns auf Twitter", widget: "string"},
            {
              label: "Footer",
              name: "footer",
              widget: "object",
              fields:
                [
                  {label: "Impressum", name: "Impressum", widget: "string"},
                  {label: "Disclaimer", name: "Disclaimer", widget: "string"},
                ]
            }
          ]
      }
  - label: "Benefits Locales"
    name: "benefits"
    folder: "src/data/benefits"
    extension: "json"
    create: true
    fields:
      - {label: "Sprache", name: "title", widget: "string"}
      - {
        label: "Benefits",
        name: "benefits",
        widget: "list",
        fields:
          [
          {
            label: "Überschrift", name: "heading", widget: "markdown"
          },
          {
            label: "Text", name: "text", widget: "markdown"
          }
          ]
      }
  - label: "Kontakt"
    name: "contact"
    files:
      - file: "src/data/contact.json"
        label: "Kontakt"
        name: "contact"
        fields:
          - {label: "Name", name: "name", widget: "string", required: false}
          - {label: "Email", name: "email", widget: "string"}
          - {label: "Phone", name: "phone", widget: "string"}
  - label: "License"
    name: "license"
    folder: "src/data/license"
    extension: "json"
    create: true
    fields:
      - {label: "Sprache", name: "title", widget: "string"}
      - {
        label: "License",
        name: "license",
        widget: "list",
        fields:
          [
          {
            label: "Überschrift", name: "heading", widget: "markdown"
          },
          {
            label: "Text", name: "text", widget: "markdown"
          }
          ]
      }
